### ISSUE TITLE
The AdobeBranchExtension still uses Branch instead of BranchSDK

### ISSUE THREAD

**Issue by edumeira** [BranchMetrics/AdobeBranchExtension-iOS#25]
### Describe the bug

The SDK is still pointing to the Branch pod, which shows as deprecated in favour of BranchSDK. 

We also started having some crashes being pointed to the SDK, but we're still investigating the details.

### Steps to reproduce

1. Include the latest version of AdobeBranchExtension in your podfile
2. Run pod install

### Expected behavior

The SDK should point to the new BranchSDK dependency

### SDK Version

1.3.6

### XCode Version

N/A

### Device

N/A

### OS

N/A

**Comment by nsingh-branch** [comment]
This is fixed in the latest update v2.0.0.
